# Stage 0, "build-stage", based on Node.js to build the frontend
FROM node:18-alpine3.15 as build
WORKDIR /app/frontend
COPY package*.json /app/
RUN npm install
COPY src/ ./src
COPY public ./public
COPY package.json package-lock.json tailwind.config.js ./
COPY .envProd ./.env
RUN npm run build

# Stage 1, based on NGINX to provide a configuration to be used with react-router
FROM nginx:alpine
COPY --from=build /app/frontend/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]