version: "3"

services:
  client:
    build: ./client
    container_name: atlas-client
    ports:
      - "3000:3000"
  server:
    build: ./server
    container_name: atlas-server
    ports:
      - "9000:9000"
    volumes:
      - ./server/storage/:/app/backend/storage/
  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
