FROM debian:bullseye
RUN apt-get update; apt-get install -y wget gnupg curl

# install mongodb
RUN wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add -
RUN echo "deb http://repo.mongodb.org/apt/debian bullseye/mongodb-org/6.0 main" > /etc/apt/sources.list.d/mongodb-org-6.0.list
RUN apt-get update; apt-get install -y mongodb-org
RUN mkdir /data
RUN mkdir /data/db

# install nodejs v14 (concurrently dependency)
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs

# setup express app files
WORKDIR /app/backend
COPY data/ ./data/
COPY models/ ./models/
COPY routes/ ./routes/
COPY scripts/ ./scripts/
COPY storage/ ./storage/
COPY package.json package-lock.json server.js ./
COPY .envProd ./.env
# install express app dependencies
RUN npm install
RUN npm install concurrently
ENV PORT = 9000
EXPOSE 9000 27017
CMD [ "npm", "run", "production" ]